2023-10-25 10:13:43,088 - INFO - [1m[37mPrograma Iniciado às [31m10:13:43[0m
2023-10-25 10:13:43,211 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-25 10:13:43,212 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-25 10:14:19,640 - INFO - [1m[37mMapa da LINHA 4 - AMARELA iniciado às [32m10:13:42[0m
2023-10-25 10:14:22,493 - INFO - [1m[37mMapa da LINHA 3 - VERMELHA iniciado às [32m10:13:42[0m
2023-10-25 10:18:03,263 - INFO - [1m[37mPrograma Iniciado às [31m10:18:03[0m
2023-10-25 10:18:03,336 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-25 10:18:03,346 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-25 10:18:19,242 - INFO - [1m[37mMapa da LINHA 5 - LILÁS iniciado às [32m10:18:03[0m
2023-10-25 10:18:27,074 - INFO - [1m[37mMapa da Rede iniciado às [32m10:18:01[0m
2023-10-26 17:34:50,187 - INFO - [1m[37mPrograma Iniciado às [31m17:34:50[0m
2023-10-26 17:34:50,294 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-26 17:34:50,295 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-26 17:34:52,976 - WARNING - There was an error managing chrome (error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: Foi forçado o cancelamento de uma conexão existente pelo host remoto. (os error 10054)); using driver found in the cache
2023-10-26 17:35:12,604 - INFO - [1m[37mMapa da LINHA 1 - AZUL iniciado às [32m17:34:49[0m
2023-10-26 17:35:37,886 - INFO - [1m[37mMapa da LINHA 2 - VERDE iniciado às [32m17:34:49[0m
2023-10-26 17:35:46,839 - INFO - [1m[37mMapa da LINHA 3 - VERMELHA iniciado às [32m17:34:49[0m
2023-10-26 17:35:55,286 - INFO - [1m[37mMapa da LINHA 4 - AMARELA iniciado às [32m17:34:49[0m
2023-10-26 17:36:08,255 - INFO - [1m[37mMapa da LINHA 5 - LILÁS iniciado às [32m17:34:49[0m
2023-10-26 17:36:20,222 - INFO - [1m[37mMapa da LINHA 7 - RUBI iniciado às [32m17:34:49[0m
2023-10-26 17:36:27,558 - INFO - [1m[37mMapa da LINHA 8 - DIAMANTE iniciado às [32m17:34:49[0m
2023-10-26 17:36:34,766 - INFO - [1m[37mMapa da LINHA 9 - ESMERALDA iniciado às [32m17:34:49[0m
2023-10-26 17:37:45,431 - INFO - [1m[37mMapa da LINHA 4 - AMARELA iniciado às [32m17:34:49[0m
2023-10-26 17:37:53,167 - INFO - [1m[37mMapa da LINHA 5 - LILÁS iniciado às [32m17:34:49[0m
2023-10-26 17:38:01,750 - INFO - [1m[37mMapa da LINHA 10 - TURQUESA iniciado às [32m17:34:49[0m
2023-10-26 17:38:09,478 - INFO - [1m[37mMapa da LINHA 11 - CORAL iniciado às [32m17:34:49[0m
2023-10-26 17:38:16,726 - INFO - [1m[37mMapa da LINHA 12 - SAFIRA iniciado às [32m17:34:49[0m
2023-10-26 17:38:26,271 - INFO - [1m[37mMapa da LINHA 13 - JADE iniciado às [32m17:34:49[0m
2023-10-26 17:38:35,391 - INFO - [1m[37mMapa da LINHA 15 - PRATA iniciado às [32m17:34:49[0m
2023-10-26 17:39:01,918 - INFO - [1m[37mMapa da LINHA 12 - SAFIRA iniciado às [32m17:34:49[0m
2023-10-30 11:29:48,139 - INFO - [1m[37mPrograma Iniciado às [31m11:29:48[0m
2023-10-30 11:29:48,279 - ERROR - C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\IcoImagePlugin.py:335: UserWarning: Image was not the expected size
2023-10-30 11:29:48,279 - ERROR -   warnings.warn("Image was not the expected size")
2023-10-30 11:30:22,636 - ERROR - Traceback (most recent call last):
2023-10-30 11:30:22,636 - ERROR -   File "c:\Users\Rafael Barbosa\OneDrive\Área de Trabalho\Sampa-4-u\main.py", line 417, in <module>
2023-10-30 11:30:22,637 - ERROR - canvas.itemconfigure(temperatura, text=get_weather())
2023-10-30 11:30:22,638 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 2959, in itemconfigure
2023-10-30 11:30:22,659 - ERROR - return self._configure(('itemconfigure', tagOrId), cnf, kw)
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,660 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR - ^
2023-10-30 11:30:22,661 - ERROR -   File "C:\Users\Rafael Barbosa\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1692, in _configure
2023-10-30 11:30:22,662 - ERROR - self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
2023-10-30 11:30:22,662 - ERROR - _tkinter
2023-10-30 11:30:22,662 - ERROR - .
2023-10-30 11:30:22,662 - ERROR - TclError
2023-10-30 11:30:22,662 - ERROR - :
2023-10-30 11:30:22,662 - ERROR - invalid command name ".!canvas"
